module.exports = {
  announcements: [
    `*You're DingDong of the day, don't fuck it up!*`,
    `*Roses are red, violets are blue, you're the DingDong so you better write a damn speech!*`,
    `*We thought about kicking you out, but since you're the DingDong now we need you to write your thoughts here!*`,
    `*You're the DingDong of the day, you have everyone's attention!*`,
    `*AAAAYYYYYYYYYY whatcha got DingDong!?*`,
    `*Only you can talk in here today, let'er rip DINGDONG!*`,
    `*There's a DingDong in all of us, and today, your DingDong is flappin' in the wind!*`,
    `*A wild DingDong appeared!!!*`,
    `*You're DingDong of the day, time to speech to all of us inferior beings!*`,
    `*Why, is that a DingDong in your pocket or are you just happy to see us?!*`,
    `*Surely today's DingDong has something to say?*`,
    `*To be a DingDong or not to be, iS ThAt eVeN a FuCkInG qUeStIoN?*`,
    `*Tread softly DingDong because you tread on our dreams!*`,
    `*If you die today, we'll all remember you as a DingDong, unless you SPEECH!*`,
    `*DingDongs, DingDongs everywhere, not really there's only one DingDong and that's you!*`,
    `*There's a crack in everything, that's how the DingDong slips in!*`,
    `*War is what happens when the DingDong fails to SPEECH!*`,
    `*The fool doth think they are wise, but the DingDong knows themself to be a fool.*`,
    `*Words are, of course, the most powerful drug used by the DingDong.*`,
    `*The great art of life is sensation, to feel a DingDong, even when it hurts.*`,
    `*Some DingDongs never go crazy, what truly horrible lives they must lead.*`,
    `*Of all the creatures that breathe and move upon the earth, nothing is bread that is stronger than the DingDong.*`,
    `*The DingDong's course is set for an uncharted sea.*`,
    `*Fill this channel with the breathings of your heart you filthy DingDong!*`,
    `*Rather than love, than money, than fame, give us the DingDong!*`,
    `*Shut your eyes and open your DingDong!*`,
    `*If you don't like someone's DingDong, play with your own!*`,
    `*Twerk first, ask questions later, it's the natural way of the DingDong.*`,
    `*The DingDong is a curious creature...*`,
    `*Fortune sides with those who DingDong!*`,
    `*One word frees us of all the weight and pain of life: That word is DingDong!*`
  ]
};
